---
# follow debian manual install: https://pkg.jenkins.io/debian-stable/

- name: Make sure aptitude is present (using apt-get)
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes
  become: true

- name: Make sure requirements are installed
  apt:
    name:
      - fontconfig
      - openjdk-17-jre
      - unzip
      - tar
      - wget
    state: present
    update_cache: yes
  become: true

- name: Make sure keyring GPG-ASC folder exists
  file:
    path: "/usr/share/keyrings/"
    state: directory
    mode: 0775
  become: true

# Return: Segmentation fault (core dumped) - exit code 139 - anyway it's create asc correctly
- name: Add Jenkins LTS GPG pubblic key
  shell:
    cmd: "wget -O /usr/share/keyrings/jenkins-keyring.asc {{ jenkins_gpg_key }}"
  become: true
  ignore_errors: True

- name: Add Jenkins ATP Repository
  shell:
    cmd: "echo \"deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]\" https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null"
  become: true

# "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))
#- name: Add Jenkins LTS GPG apt key
#  apt_key:
#    url: "{{ jenkins_gpg_key }}"
#    state: present
#    keyring: "/usr/share/keyrings/jenkins-keyring.asc"
#  become: true
#
#- name: Add Jenkins Repository
#  apt_repository:
#    repo: deb https://pkg.jenkins.io/debian-stable binary/
#    state: present
#    filename: jenkins

- name: Install Jenkins LTS
  apt:
    name:
      - jenkins
    state: present
    update_cache: yes
  notify: start jenkins
