---
- name: assert supported distributions and versions (Ubuntu LTS version)
  assert:
    that:
      - ansible_distribution == 'Ubuntu'
      - ansible_distribution_major_version|int in [20, 22]
    fail_msg: "This role only supports Ubuntu 20.04 LTS or Ubuntu 22.04 LTS."
    success_msg: "Supported Ubuntu version found."

- name: Set UTC timezone
  timezone:
    name: Etc/UTC
  become: true

- name: Install Jenkins for debain-like OS
  include_tasks: jenkins_debian.yml
  when: 
    - ansible_os_family == "Debian"
