---
- name: Create Maven directory
  file:
    path: "{{ jenkins_maven_dir }}"
    state: directory
    owner: 'jenkins'

- name: Create Maven 3.8.2 directory
  file:
    path: "{{ jenkins_maven_dir }}/maven-3.8.2"
    state: directory
    owner: 'jenkins'

- name: Download Maven 3.8.2 with checksum (sha512)
  get_url:
    url: https://dlcdn.apache.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz
    dest: "{{ jenkins_maven_dir }}/maven-3.8.2.tar.gz"
    checksum: sha512:b0bf39460348b2d8eae1c861ced6c3e8a077b6e761fb3d4669be5de09490521a74db294cf031b0775b2dfcd57bd82246e42ce10904063ef8e3806222e686f222

- name: Extract Maven 3.8.2
  unarchive:
    src: "{{ jenkins_maven_dir }}/maven-3.8.2.tar.gz"
    dest: "{{ jenkins_maven_dir }}"
    remote_src: yes
